# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Sep 28 19:31:00 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(498, 505)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.num_puzzles = QtGui.QTextEdit(self.centralWidget)
        self.num_puzzles.setGeometry(QtCore.QRect(310, 49, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.num_puzzles.setFont(font)
        self.num_puzzles.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.num_puzzles.setObjectName("num_puzzles")
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.puzzles_per_page = QtGui.QComboBox(self.centralWidget)
        self.puzzles_per_page.setGeometry(QtCore.QRect(310, 120, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.puzzles_per_page.setFont(font)
        self.puzzles_per_page.setObjectName("puzzles_per_page")
        self.puzzles_per_page.addItem("")
        self.puzzles_per_page.addItem("")
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.difficulty = QtGui.QComboBox(self.centralWidget)
        self.difficulty.setGeometry(QtCore.QRect(310, 190, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.difficulty.setFont(font)
        self.difficulty.setObjectName("difficulty")
        self.difficulty.addItem("")
        self.difficulty.addItem("")
        self.difficulty.addItem("")
        self.difficulty.addItem("")
        self.difficulty.addItem("")
        self.include_solutions = QtGui.QCheckBox(self.centralWidget)
        self.include_solutions.setGeometry(QtCore.QRect(320, 250, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.include_solutions.setFont(font)
        self.include_solutions.setText("")
        self.include_solutions.setObjectName("include_solutions")
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(30, 240, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.go_button = QtGui.QPushButton(self.centralWidget)
        self.go_button.setGeometry(QtCore.QRect(360, 310, 113, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.go_button.setFont(font)
        self.go_button.setObjectName("go_button")
        self.progressBar = QtGui.QProgressBar(self.centralWidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 410, 481, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progress_label = QtGui.QLabel(self.centralWidget)
        self.progress_label.setGeometry(QtCore.QRect(10, 390, 481, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progress_label.setFont(font)
        self.progress_label.setObjectName("progress_label")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 498, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuDesktop_Sudoku_Generator = QtGui.QMenu(self.menuBar)
        self.menuDesktop_Sudoku_Generator.setObjectName("menuDesktop_Sudoku_Generator")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuDesktop_Sudoku_Generator.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Number of puzzles:", None, QtGui.QApplication.UnicodeUTF8))
        self.num_puzzles.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:30pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">4</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Puzzles per page:", None, QtGui.QApplication.UnicodeUTF8))
        self.puzzles_per_page.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.puzzles_per_page.setItemText(1, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Difficulty:", None, QtGui.QApplication.UnicodeUTF8))
        self.difficulty.setItemText(0, QtGui.QApplication.translate("MainWindow", "Random", None, QtGui.QApplication.UnicodeUTF8))
        self.difficulty.setItemText(1, QtGui.QApplication.translate("MainWindow", "Easy", None, QtGui.QApplication.UnicodeUTF8))
        self.difficulty.setItemText(2, QtGui.QApplication.translate("MainWindow", "Medium", None, QtGui.QApplication.UnicodeUTF8))
        self.difficulty.setItemText(3, QtGui.QApplication.translate("MainWindow", "Hard", None, QtGui.QApplication.UnicodeUTF8))
        self.difficulty.setItemText(4, QtGui.QApplication.translate("MainWindow", "Very Hard", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Include Solutions", None, QtGui.QApplication.UnicodeUTF8))
        self.go_button.setText(QtGui.QApplication.translate("MainWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.progress_label.setText(QtGui.QApplication.translate("MainWindow", "Include Solutions", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDesktop_Sudoku_Generator.setTitle(QtGui.QApplication.translate("MainWindow", "Desktop Sudoku Generator", None, QtGui.QApplication.UnicodeUTF8))

